
@HostAddress = https://localhost:7076
GET {{HostAddress}}/api/Dinners
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1MjE1ZDc3NS0zYmUzLTQxNjctYTVhMi1lZDU2YjZhY2VlYmMiLCJnaXZlbl9uYW1lIjoic3RyaW5nIiwiZmFtaWx5X25hbWUiOiJzdHJpbmciLCJqdGkiOiI0Yjc2YWUyMy0yYmU4LTQ5NjYtYjBiNy01ZmZiOTYzMjExNDgiLCJleHAiOjE3Mzk4MDY1ODYsImlzcyI6IkNsZWFuQXJjaGl0ZWN0dXJlQWxpSmFmYXJpeGNzIiwiYXVkIjoiQ2xlYW5BcmNoaXRlY3R1cmVBbGlKYWZhcml4Y3NBdWRpZW5jZSJ9.rtSKLGZQD9sAxXdx4MRitD-BhREe61WglyZYxcet4E4